-- V33: Seed dishes from dev environment
-- Must run after V32 (ingredients)

-- Insert dishes (195 records)
INSERT INTO dishes (id, name, description, default_quarts_per_thaali_unit, active, created_at, updated_at) VALUES
(1, 'Afghani Chicken', NULL, 1.00, true, now(), now()),
(2, 'Afghani bread', NULL, 1.00, true, now(), now()),
(3, 'Black bean Veggie Pesto Chicken Pasta', NULL, 1.00, true, now(), now()),
(4, 'Cauliflower steaks w/mashed and picatta sauce', NULL, 1.00, true, now(), now()),
(5, 'Chinese chicken stirfry', NULL, 1.00, true, now(), now()),
(6, 'Falafel with rice', NULL, 1.00, true, now(), now()),
(7, 'General - kheer', NULL, 1.00, true, now(), now()),
(8, 'General - pantry spice', NULL, 1.00, true, now(), now()),
(9, 'General - pantry staple', NULL, 1.00, true, now(), now()),
(10, 'General Items - stock adjust', NULL, 1.00, true, now(), now()),
(11, 'Hyderbadi baingan', NULL, 1.00, true, now(), now()),
(12, 'Impossible chili', NULL, 1.00, true, now(), now()),
(13, 'Indian-style chicken fried rice', NULL, 1.00, true, now(), now()),
(14, 'Indonesian rendang curry (goat)', NULL, 1.00, true, now(), now()),
(15, 'Lahori chicken', NULL, 1.00, true, now(), now()),
(16, 'Mexican mac and cheese', NULL, 1.00, true, now(), now()),
(17, 'Mideast Chicken and Rice', NULL, 1.00, true, now(), now()),
(18, 'North Indian egg curry', NULL, 1.00, true, now(), now()),
(19, 'SEHORI butter', NULL, 1.00, true, now(), now()),
(20, 'SEHORI eggs', NULL, 1.00, true, now(), now()),
(21, 'SEHORI roti', NULL, 1.00, true, now(), now()),
(22, 'SEHORI tea items', NULL, 1.00, true, now(), now()),
(23, 'South Indian egg curry', NULL, 1.00, true, now(), now()),
(24, 'Sri Lankan chicken curry', NULL, 1.00, true, now(), now()),
(25, 'Swedish meatballs', NULL, 1.00, true, now(), now()),
(26, 'Thai beef stirfry', NULL, 1.00, true, now(), now()),
(27, 'Thai chicken stirfry', NULL, 1.00, true, now(), now()),
(28, 'Thai green curry (chicken)', NULL, 1.00, true, now(), now()),
(29, 'West African peanut chicken curry', NULL, 1.00, true, now(), now()),
(30, 'achaar chicken', NULL, 1.00, true, now(), now()),
(31, 'achaar gosht', NULL, 1.00, true, now(), now()),
(32, 'akhni pulao', NULL, 1.00, true, now(), now()),
(33, 'aloo baingan', NULL, 1.00, true, now(), now()),
(34, 'aloo bhajhi', NULL, 1.00, true, now(), now()),
(35, 'aloo gobi', NULL, 1.00, true, now(), now()),
(36, 'aloo matar', NULL, 1.00, true, now(), now()),
(37, 'aloo tarkari (rai wala)', NULL, 1.00, true, now(), now()),
(38, 'baked chicken tenders', NULL, 1.00, true, now(), now()),
(39, 'baked herb chicken', NULL, 1.00, true, now(), now()),
(40, 'batura bread', NULL, 1.00, true, now(), now()),
(41, 'bbq chicken legs', NULL, 1.00, true, now(), now()),
(42, 'bbq chicken sliders', NULL, 1.00, true, now(), now()),
(43, 'beef chili', NULL, 1.00, true, now(), now()),
(44, 'bhinda masala', NULL, 1.00, true, now(), now()),
(45, 'blueberry poundcake trifle', NULL, 1.00, true, now(), now()),
(46, 'bread - baguette', NULL, 1.00, true, now(), now()),
(47, 'bread - lavash', NULL, 1.00, true, now(), now()),
(48, 'bread - naan', NULL, 1.00, true, now(), now()),
(49, 'bread - paratha', NULL, 1.00, true, now(), now()),
(50, 'bread - sheermal', NULL, 1.00, true, now(), now()),
(51, 'butter chicken', NULL, 1.00, true, now(), now()),
(52, 'cabbage stirfry', NULL, 1.00, true, now(), now()),
(53, 'cauliflower tikka masala', NULL, 1.00, true, now(), now()),
(54, 'chana doodhi', NULL, 1.00, true, now(), now()),
(55, 'chana gosht', NULL, 1.00, true, now(), now()),
(56, 'chawla pulao', NULL, 1.00, true, now(), now()),
(57, 'chicen kaari', NULL, 1.00, true, now(), now()),
(58, 'chicken biryani', NULL, 1.00, true, now(), now()),
(59, 'chicken corn soup', NULL, 1.00, true, now(), now()),
(60, 'chicken curry', NULL, 1.00, true, now(), now()),
(61, 'chicken fajita', NULL, 1.00, true, now(), now()),
(62, 'chicken gumbo', NULL, 1.00, true, now(), now()),
(63, 'chicken hakka noodles', NULL, 1.00, true, now(), now()),
(64, 'chicken jalfrezi', NULL, 1.00, true, now(), now()),
(65, 'chicken kheema bhaji', NULL, 1.00, true, now(), now()),
(66, 'chicken khurdhi', NULL, 1.00, true, now(), now()),
(67, 'chicken lagan ni seekh', NULL, 1.00, true, now(), now()),
(68, 'chicken legs in peanut sauce', NULL, 1.00, true, now(), now()),
(69, 'chicken legs in red sauce', NULL, 1.00, true, now(), now()),
(70, 'chicken legs in white sauce', NULL, 1.00, true, now(), now()),
(71, 'chicken manchurian', NULL, 1.00, true, now(), now()),
(72, 'chicken pasta casserole', NULL, 1.00, true, now(), now()),
(73, 'chicken picatta', NULL, 1.00, true, now(), now()),
(74, 'chicken quesadilla', NULL, 1.00, true, now(), now()),
(75, 'chicken tikka masala', NULL, 1.00, true, now(), now()),
(76, 'chicken tortilla soup w/rice and beans', NULL, 1.00, true, now(), now()),
(77, 'chicken vegetable pulao', NULL, 1.00, true, now(), now()),
(78, 'chicken veggie casserole', NULL, 1.00, true, now(), now()),
(79, 'chickoli', NULL, 1.00, true, now(), now()),
(80, 'chilli chicken', NULL, 1.00, true, now(), now()),
(81, 'chola batura', NULL, 1.00, true, now(), now()),
(82, 'coleslaw', NULL, 1.00, true, now(), now()),
(83, 'creamy pasta primavera', NULL, 1.00, true, now(), now()),
(84, 'daal chawal', NULL, 1.00, true, now(), now()),
(85, 'daal gosht', NULL, 1.00, true, now(), now()),
(86, 'daal makhani', NULL, 1.00, true, now(), now()),
(87, 'daal tadka (daal fry)', NULL, 1.00, true, now(), now()),
(88, 'dahi kadhi', NULL, 1.00, true, now(), now()),
(89, 'dhaba chana dal fry', NULL, 1.00, true, now(), now()),
(90, 'doodhi tarkari', NULL, 1.00, true, now(), now()),
(91, 'dum aloo', NULL, 1.00, true, now(), now()),
(92, 'fruit - apple', NULL, 1.00, true, now(), now()),
(93, 'fruit - banana', NULL, 1.00, true, now(), now()),
(94, 'fruit - blueberries', NULL, 1.00, true, now(), now()),
(95, 'fruit - buyer''s choice', NULL, 1.00, true, now(), now()),
(96, 'fruit - kiwi', NULL, 1.00, true, now(), now()),
(97, 'fruit - orange', NULL, 1.00, true, now(), now()),
(98, 'fruit - peach', NULL, 1.00, true, now(), now()),
(99, 'fruit - pear', NULL, 1.00, true, now(), now()),
(100, 'fruit - plum', NULL, 1.00, true, now(), now());

INSERT INTO dishes (id, name, description, default_quarts_per_thaali_unit, active, created_at, updated_at) VALUES
(101, 'general - tres leches caramel cake', NULL, 1.00, true, now(), now()),
(102, 'gosht biryani', NULL, 1.00, true, now(), now()),
(103, 'gosht kaari', NULL, 1.00, true, now(), now()),
(104, 'gosht ni tarkari', NULL, 1.00, true, now(), now()),
(105, 'green bean aloo curry', NULL, 1.00, true, now(), now()),
(106, 'green chicken (caju ni murghi)', NULL, 1.00, true, now(), now()),
(107, 'green gosht (caju ni gosht)', NULL, 1.00, true, now(), now()),
(108, 'guvar aloo', NULL, 1.00, true, now(), now()),
(109, 'haleem', NULL, 1.00, true, now(), now()),
(110, 'haleem - garnish', NULL, 1.00, true, now(), now()),
(111, 'handi chicken', NULL, 1.00, true, now(), now()),
(112, 'ice cream', NULL, 1.00, true, now(), now()),
(113, 'kaleji ni tarkari', NULL, 1.00, true, now(), now()),
(114, 'karahi chicken', NULL, 1.00, true, now(), now()),
(115, 'kebabs, frozen (ready-made)', NULL, 1.00, true, now(), now()),
(116, 'khajoor', NULL, 1.00, true, now(), now()),
(117, 'kheema aloo matar', NULL, 1.00, true, now(), now()),
(118, 'kheema bhaji', NULL, 1.00, true, now(), now()),
(119, 'kheema biryani', NULL, 1.00, true, now(), now()),
(120, 'kheema khichdhi', NULL, 1.00, true, now(), now()),
(121, 'kheema patvelia', NULL, 1.00, true, now(), now()),
(122, 'kheema pau', NULL, 1.00, true, now(), now()),
(123, 'khichdi', NULL, 1.00, true, now(), now()),
(124, 'kofta curry', NULL, 1.00, true, now(), now()),
(125, 'kushari', NULL, 1.00, true, now(), now()),
(126, 'lagan ni seekh', NULL, 1.00, true, now(), now()),
(127, 'lasagne with meat sauce', NULL, 1.00, true, now(), now()),
(128, 'lemon olive chicken tagine', NULL, 1.00, true, now(), now()),
(129, 'malvi gosht', NULL, 1.00, true, now(), now()),
(130, 'masoor daal', NULL, 1.00, true, now(), now()),
(131, 'masoor daal w/gosht', NULL, 1.00, true, now(), now()),
(132, 'masoor pulao', NULL, 1.00, true, now(), now()),
(133, 'matar paneer', NULL, 1.00, true, now(), now()),
(134, 'mattho', NULL, 1.00, true, now(), now()),
(135, 'mezze - hummus', NULL, 1.00, true, now(), now()),
(136, 'mezze - pita bread', NULL, 1.00, true, now(), now()),
(137, 'mezze - stuffed grape leaves', NULL, 1.00, true, now(), now()),
(138, 'mezze - tapenade', NULL, 1.00, true, now(), now()),
(139, 'mezze - tzaziki', NULL, 1.00, true, now(), now()),
(140, 'mithaas - caju pak', NULL, 1.00, true, now(), now()),
(141, 'mithaas - fruit custard', NULL, 1.00, true, now(), now()),
(142, 'mithaas - gajar nu halwo', NULL, 1.00, true, now(), now()),
(143, 'mithaas - gulab jamun', NULL, 1.00, true, now(), now()),
(144, 'mithaas - ice cream', NULL, 1.00, true, now(), now()),
(145, 'mithaas - sev zarda', NULL, 1.00, true, now(), now()),
(146, 'mithaas - sooji halwa', NULL, 1.00, true, now(), now()),
(147, 'mithaas - tuxedo cake', NULL, 1.00, true, now(), now()),
(148, 'mixed daal', NULL, 1.00, true, now(), now()),
(149, 'mixed daal gosht', NULL, 1.00, true, now(), now()),
(150, 'mixed vegetable tarkari', NULL, 1.00, true, now(), now()),
(151, 'moong pulao', NULL, 1.00, true, now(), now()),
(152, 'mutton khurdhi', NULL, 1.00, true, now(), now()),
(153, 'mutton paya', NULL, 1.00, true, now(), now()),
(154, 'navratan korma', NULL, 1.00, true, now(), now()),
(155, 'nihari', NULL, 1.00, true, now(), now()),
(156, 'nut packet', NULL, 1.00, true, now(), now()),
(157, 'olives, green', NULL, 1.00, true, now(), now()),
(158, 'orange masoor daal', NULL, 1.00, true, now(), now()),
(159, 'paav bhaji', NULL, 1.00, true, now(), now()),
(160, 'paav bhaji - buns', NULL, 1.00, true, now(), now()),
(161, 'pakorda', NULL, 1.00, true, now(), now()),
(162, 'palak paneer', NULL, 1.00, true, now(), now()),
(163, 'palida', NULL, 1.00, true, now(), now()),
(164, 'panang curry (chicken)', NULL, 1.00, true, now(), now()),
(165, 'paneer jalfrezi', NULL, 1.00, true, now(), now()),
(166, 'paneer karahi', NULL, 1.00, true, now(), now()),
(167, 'paneer makhani', NULL, 1.00, true, now(), now()),
(168, 'paneer tikka masala', NULL, 1.00, true, now(), now()),
(169, 'pesto ravioli', NULL, 1.00, true, now(), now()),
(170, 'pollo guisado', NULL, 1.00, true, now(), now()),
(171, 'punjabi baingan ka bharta', NULL, 1.00, true, now(), now()),
(172, 'raita', NULL, 1.00, true, now(), now()),
(173, 'ravioli Florentine', NULL, 1.00, true, now(), now()),
(174, 'salad - English cumbers', NULL, 1.00, true, now(), now()),
(175, 'salad - Romaine lettuce', NULL, 1.00, true, now(), now()),
(176, 'salad - bell peppers', NULL, 1.00, true, now(), now()),
(177, 'salad - carrots', NULL, 1.00, true, now(), now()),
(178, 'salad - mixed greens lettuce', NULL, 1.00, true, now(), now()),
(179, 'shahi tukda', NULL, 1.00, true, now(), now()),
(180, 'sheer khurma', NULL, 1.00, true, now(), now()),
(181, 'sloppy joes', NULL, 1.00, true, now(), now()),
(182, 'sooji halwa', NULL, 1.00, true, now(), now()),
(183, 'sweet and sour chicken over rice', NULL, 1.00, true, now(), now()),
(184, 'tahini sauce', NULL, 1.00, true, now(), now()),
(185, 'tandoori chicken legs', NULL, 1.00, true, now(), now()),
(186, 'tindoora fry', NULL, 1.00, true, now(), now()),
(187, 'tomato soup', NULL, 1.00, true, now(), now()),
(188, 'vegetable biryani', NULL, 1.00, true, now(), now()),
(189, 'vegetable hakka noodles', NULL, 1.00, true, now(), now()),
(190, 'vegetable korma', NULL, 1.00, true, now(), now()),
(191, 'vegetable lasagne', NULL, 1.00, true, now(), now()),
(192, 'white rice', NULL, 1.00, true, now(), now()),
(193, 'whole chicken in white sauce', NULL, 1.00, true, now(), now()),
(194, 'whole chicken keit (red sauce)', NULL, 1.00, true, now(), now()),
(195, 'mutton kheema khichdi', NULL, 1.00, true, now(), now());

SELECT setval('dishes_id_seq', (SELECT MAX(id) FROM dishes));
